version: "3.9"

services:
  app:
    build: .
    container_name: 'springboot_api'
    depends_on:
      - 'db'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/music_db'
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: '12345678'
    ports:
      - "8080:8080"
    restart: 'always'
    networks:
      - 'm_network'

  db:
    image: 'postgres:latest'
    container_name: 'local_postgres'
    environment:
      - 'POSTGRES_DB=music_db'
      - 'POSTGRES_PASSWORD=12345678'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    restart: 'always'
    networks:
      - 'm_network'
    volumes:
      - 'postgres_data:/var/lib/postgresql'

volumes:
  postgres_data:

networks:
  m_network:
    driver: 'bridge'

